[package]
name = "blockforge"
version = "0.0.1"

[dependencies]
InitiaStdlib = { local = "deps/movevm/precompile/modules/initia_stdlib" }
MoveStdlib = { local = "deps/movevm/precompile/modules/move_stdlib" }

[addresses]
blockforge = "_"
std = "0x1"
